version: '3'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "127.0.0.1:5000:5000"  # Redirection du port 5000 de l'hôte vers le port 5000 du conteneur
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      FLASK_APP: "src/app.py"  # Chemin vers votre fichier app.py
    env_file:
      - .env
    command: flask run --host=0.0.0.0
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    volumes:
      - ./conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - 8080:8080
